spring:
  datasource:
    url: jdbc:postgresql://database-1.c3ua8sgk2lc4.us-east-1.rds.amazonaws.com:5432/base
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  error:
    include-message: always

openai:
  api:
    key: key
    url: https://api.openai.com/v1/chat/completions